export type AppointmentStatus = 'pending' | 'confirmed' | 'cancelled';

/**
 * Access is binary: a profile row means admin, no row means no access.
 * The `staff` role was removed in docs/schema-v3.md.
 */
export interface Profile {
  id: string;
  full_name: string;
  created_at: string;
  updated_at: string;
}

/** One row per patient from search_patients(), for the phone type-ahead. */
export interface PatientMatch {
  phone_digits: string;
  phone: string;
  patient_name: string;
  email: string | null;
  total: number;
  last_visit: string;
}

/** Single-row table holding admin-configurable booking rules. */
export interface ClinicSettings {
  id: boolean;
  /** How many patients may book the same time slot. */
  max_per_slot: number;
  updated_at: string;
  updated_by: string | null;
}

export interface Appointment {
  id: string;
  patient_name: string;
  phone: string;
  /** Generated column: last 10 digits of `phone`. Read-only; the patient grouping key. */
  phone_digits: string;
  email: string | null;
  appointment_date: string;
  appointment_time: string;
  message: string | null;
  status: AppointmentStatus;
  /** Admin-only: exempts the row from OPD-hours and slot-alignment checks. */
  override_opd: boolean;
  created_at: string;
  updated_at: string;
  updated_by: string | null;
}

export interface ContactInquiry {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  message: string;
  is_resolved: boolean;
  created_at: string;
  resolved_at: string | null;
  resolved_by: string | null;
  updated_at: string;
}

export interface Event {
  id: string;
  title: string;
  description: string;
  start_date: string;
  end_date: string | null;
  image_url: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Testimonial {
  id: string;
  patient_name: string;
  rating: number;
  review: string;
  approved: boolean;
  created_at: string;
  approved_by: string | null;
  updated_at: string;
}

/**
 * `phone_digits` is generated by Postgres and must never be sent in a write.
 * `override_opd` is optional: it has a database default, and the admin dialog
 * omits it entirely unless the emergency flag is actually in play.
 */
export type AppointmentInsert = Omit<
  Appointment,
  'id' | 'created_at' | 'updated_at' | 'updated_by' | 'phone_digits' | 'override_opd'
> & { override_opd?: boolean };
/** Editable appointment fields; `updated_by`/`updated_at` are set by the action and trigger. */
export type AppointmentUpdate = Partial<AppointmentInsert>;

